# Generated by Django 3.2.6 on 2021-09-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_booking_shards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='booking_shards',
            field=models.JSONField(default=dict),
        ),
    ]
